import type { Metadata } from "next";
import PageMenu from "@/components/page-menu/PageMenu";
import Header from "@/components/header/Header";
import "../globals.scss";
import SmoothScrolling from "@/app/SmoothScrolling";
import ModalMenu from "@/components/_modals/modal-menu/ModalMenu";
import ModalContacts from "@/components/_modals/modal-contacts/ModalContacts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Header />
        <SmoothScrolling>{children}</SmoothScrolling>
        <ModalMenu/>
        <ModalContacts/>
      </body>
    </html>
  );
}
